### ISSUE TITLE
Pre-Qualification nie działa

### ISSUE THREAD

**Issue by Danmark25** [Jonek2208/Open-Ski-Jumping#15]
Pre-Qualification powinien puścić tylko (jeżeli ustawiliśmy 8 zawodników) 8 zawodników do konkursu..

W praktyce puszcza wszystkich a gracz musi sobie wyłączać ich ręcznie.

**Comment by Jonek2208** [comment]
A zobacz to teraz, bo przy pre-qual trzeba jeszcze inlimit ustawić

**Comment by Danmark25** [comment]
Aktualizacja: (robiłem to na Alpha 12)

Pre-qualification nadal nie działa (nawet jak ustawiłem in-limit, że najlepsza 4 z poprzedniej skoczni przechodzi dalej to i tak wchodzi piątka)

**Comment by Jonek2208** [comment]
Zobacz to na alpha 15
