### ISSUE TITLE
Mistrzostwa się nie kończą po zagranych skoczniach

### ISSUE THREAD

**Issue by Danmark25** [Jonek2208/Open-Ski-Jumping#16]
Wcześniej kończyło zawody z usunięciem zapisu.. Obecnie

Pojawia się drużynowa Planica

![image](https://user-images.githubusercontent.com/59868034/88462094-17a97d80-cea9-11ea-99a4-ae105504e023.png)

Która i tak nie działa

![image](https://user-images.githubusercontent.com/59868034/88462109-2728c680-cea9-11ea-98e1-7eb846c1eb68.png)

**Comment by JacobItaly** [comment]
Da tak samo pojawia sie planica jak sie skonczy

**Comment by Jonek2208** [comment]
To, że nie działa, to wiadome, bo wychodzi poza zakres numer konkursu. Planica jest tam, bo tak jest defaultowo, czyli będę musiał dać jakieś info, że koniec sezonu itp itd

**Comment by Jonek2208** [comment]
poprawione w 0.5.0a16
