### ISSUE TITLE
Komenda "outLimit" jest uszkodzona (nie pozwala na więcej skoczków)

### ISSUE THREAD

**Issue by Danmark25** [Jonek2208/Open-Ski-Jumping#17]
Komenda outLimit działa w taki sposób, że jak jest więcej niż jedna runda to eliminuje słabszych skoczków do następnej.

Tylko jak są presety typu Trial Round, Qualification albo Qualification KO (Gdzie jest tylko 1 runda), to jeżeli jest więcej niż pozwala komenda outLimit... Gra uznaje że nie przepuści dalej i się wysypuje (pomaga tylko klawisz Escape).

Jeżeli chcę się odtworzyć błąd to wystarczy skoczyć 31 zawodnikami na Trial Round (gdzie dopuszczalnych jest tylko 30)

**Comment by Jonek2208** [comment]
To już powinno działać od a11
