### ISSUE TITLE
Coś się popsuło w wersji a11?

### ISSUE THREAD

**Issue by JacobItaly** [Jonek2208/Open-Ski-Jumping#18]
Czy to intencjonalnie wypuszczona wersja "developerska" - że połowa rzeczy nie działa i jest po to, żeby tak sobie testować, ale po kolei:

v0.5.0a11: 
**game breaks after round where jumpers are eliminated** (???)
**jumper suit / skis / helmet colors**
Added:
(???) bibs colors
**working pre-qualifications** (???)

Pogrubione rzeczy sugerują, że nie da się na ten moment ich sprawdzić, lub nie działają - a ??? oznacza że nie sprawdziłem:
**Game breaks after round where jumpers are eliminated** - tego nie można sprawdzić, ponieważ nie da się pominąć skoku klikając "R" - gra nic sobie z tego nie robi
**jumper suit / skis / helmet colors** - To nie wiem co to dokładnie oznacza, coś o kolorkach kombinezonów itp. ale dalej nie daje to żadnego efektu, jak zmieniamy ich skoczkom/gdy tworzymy skoczka
**working pre-qualifications** - Tego też nie można sprawdzić (wyjaś. w 1 rzeczy)
**Gdy rozpoczynamy konkurs, powinno pokazać się zdj. nazwisko imie itp, ale to się nie pokazuje**

**Comment by Danmark25** [comment]
Niestety takie są wady Unity, jeżeli naprawione są jedne rzeczy, to inne się psują

Ale dzięki za informację, przynajmniej pozostanę na A10 na ten moment

**Comment by Jonek2208** [comment]
No tylko mi nie chodzi o pomijanie skoków celowe, tylko o ten bug z A10 gdzie się gra crashowala jak ktoś odpadał
