### ISSUE TITLE
Nie można zrobić pucharu świata

### ISSUE THREAD

**Issue by januszgier** [Jonek2208/Open-Ski-Jumping#24]
Kiedy po kilku skoczniach chcesz skakać na innej skoczni to wtedy wyskakuje new hill i jest dziwna tabelka na której wyskakuje kamil stoch z odległościami 243,243,243,243 i przeliczniki za wiatr nawet kiedy nie skoczyłeś

**Comment by Jonek2208** [comment]
Takie coś to są domyślne wartości grafik, także to nie ma nic wspólnego z błędem. Błąd jest gdzieś w przeliczaniu kalendarzy i list startowych. Poza tym żebym mógł cokolwiek z tym zrobić, to potrzebuje calendars.json i saves.json
