### ISSUE TITLE
Brak możliwości ustawienia rozdzielczości/trybu okienkowego

### ISSUE THREAD

**Issue by Danmark25** [Jonek2208/Open-Ski-Jumping#5]
W wersji 0.4.5 był launcher który pozwalał na zmianę rozdzielczości, wybór między okienkiem a pełnym ekranem, oraz zmianę jakości tekstur.

Teraz gra wymusza pełny ekran i maksymalną rozdzielczość z pulpitu..

**Comment by Jonek2208** [comment]
jest od alpha 15
