### ISSUE TITLE
Problem z tworzeniem kalendarza

### ISSUE THREAD

**Issue by Danmark25** [Jonek2208/Open-Ski-Jumping#7]
Można usunąć utworzone wcześniej kalendarze, ale nie można utworzyć nowych.

+ znak "+" pozwala na nazwanie kalendarza ale nie ma żadnych opcji, które pozwolą go edytować.

**Comment by Danmark25** [comment]
Po ponownym włączeniu gry opcja ta się pojawiła, ale musiałem przywrócić wcześniejsze kalendarze

**Comment by Danmark25** [comment]
Przywracam problem, ponieważ jest nadal występuje..

Chodzi o to że jak się robi nowy kalendarz, to opcja jego edytowania się nie pojawia.. Dopiero restart gry odblokowuje edytowanie

**Comment by Jonek2208** [comment]
Jak to teraz wygląda?
