### ISSUE TITLE
Kobieta ma zbugowaną fizykę

### ISSUE THREAD

**Issue by Danmark25** [Jonek2208/Open-Ski-Jumping#8]
Zrobiłem dwóch skoczków (kobietę i mężczyżnę)

Zauważyłem podczas gry, że kobietą nie można się w ogóle ruszyć (A co za tym idzie) jej skoki zawsze będą niewybite, natomiast mężczyzna działa normalnie.

**Comment by Jonek2208** [comment]
Działa już
